apiVersion: networking.metal.ironcore.dev/v1alpha1
kind: Switch
metadata:
  name: spine-1
spec:
  management:
    host: 192.0.2.10
    port: "50051"
    credentials:
      name: spine-1-creds
  macAddress: "aa:bb:cc:dd:ee:ff"
  ports:
    - name: Ethernet0
    - name: Ethernet4
